# Student Adaptivity Analysis

# To get an idea about the effectiveness of online education

## During the Covid-19 phase everything went on the online platform even the education system. Students whole education was completely on the online mode. This project shows how the students were able to adapt the online mode of education based on several factors taken into consideration. So the outcome is Prediction of Students Adaptivity Level in Online Education using Machine Learning Model

In [1]:
import pandas as pd 
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import DecisionTreeClassifier

In [2]:
data=pd.read_csv(r"C:\Users\Jay Rathod\Downloads\Student_Adaptivity_preProcessed.csv")

In [3]:
data.head()

Gender  Age  Education Level  Institution Type  IT Student  Location  \
0       0    3                2                 1           0         1   
1       1    3                2                 1           0         1   
2       1    2                0                 0           0         1   
3       1    1                1                 1           0         1   
4       1    2                1                 1           0         1   

   Load-shedding  Financial Condition  Internet Type  Network Type  \
0              1                    0              1             2   
1              0                    0              0             2   
2              1                    0              1             2   
3              1                    0              0             2   
4              1                    1              0             1   

   Class Duration  Self Lms  Device  Adaptivity Level  
0               2         0       2                 1  
1               1         1       1                 1  
2               1         0       1                 1  
3               1         0       1                 1  
4               0         0       1                 0

In [4]:
data.shape

(1205, 14)

In [5]:
X=data.values[:,:-1]
Y=data.values[:,-1]

In [6]:
scaler=StandardScaler()

In [7]:
X=scaler.fit_transform(X)

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,random_state=10,test_size=0.2)

In [9]:
print(X_train.shape,X_test.shape,Y_train.shape,Y_test.shape)

(964, 13) (241, 13) (964,) (241,)


In [10]:
print("Before OverSampling, counts of label '1': ", (sum(Y_train == 1)))
print("Before OverSampling, counts of label '0': ", (sum(Y_train == 0)))
print("Before OverSampling, counts of label '2': ", (sum(Y_train == 2)))

# import SMOTE from imblearn library
from imblearn.over_sampling import SMOTE
sm = SMOTE(random_state = 10,k_neighbors=5)  #select any 5 observation and create synthetic data
X_train_res, Y_train_res = sm.fit_resample(X_train, Y_train)  #fit_resample will only work on training data
  
print('After OverSampling, the shape of train_X: ', (X_train_res.shape))
print('After OverSampling, the shape of train_y: ', (Y_train_res.shape))
  
print("After OverSampling, counts of label '1': ", (sum(Y_train_res == 1)))
print("After OverSampling, counts of label '0': ", (sum(Y_train_res == 0)))
print("After OverSampling, counts of label '2': ", (sum(Y_train_res == 2)))

Before OverSampling, counts of label '1':  488
Before OverSampling, counts of label '0':  395
Before OverSampling, counts of label '2':  81
After OverSampling, the shape of train_X:  (1464, 13)
After OverSampling, the shape of train_y:  (1464,)
After OverSampling, counts of label '1':  488
After OverSampling, counts of label '0':  488
After OverSampling, counts of label '2':  488


In [11]:
Dt=DecisionTreeClassifier(criterion="gini",random_state=10,splitter="best")
# fit the model 
Dt.fit(X_train_res,Y_train_res)
Y_pred=Dt.predict(X_test)

In [12]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
cm=confusion_matrix(Y_test,Y_pred)
print("Confusion matrix by Decision Tree :\n",cm)
class_r=classification_report(Y_test,Y_pred)
print("Classfication rep by Decision Tree :")
print(class_r)
acc_s=accuracy_score(Y_test,Y_pred)
print("Accuracy score by  Decision Tree :",acc_s)

Confusion matrix by Decision Tree :
 [[ 79   2   4]
 [  3 124  10]
 [  0   0  19]]
Classfication rep by Decision Tree :
              precision    recall  f1-score   support

           0       0.96      0.93      0.95        85
           1       0.98      0.91      0.94       137
           2       0.58      1.00      0.73        19

    accuracy                           0.92       241
   macro avg       0.84      0.94      0.87       241
weighted avg       0.94      0.92      0.93       241

Accuracy score by  Decision Tree : 0.921161825726141


In [13]:
Dt.score(X_train_res,Y_train_res)

0.9371584699453552

In [14]:
print(list(zip(data.columns[0:-1],Dt.feature_importances_*100)))

[('Gender', 5.748109332600738), ('Age', 14.387003537488049), ('Education Level', 6.041567446434956), ('Institution Type', 7.506362755652608), ('IT Student', 5.198706342929854), ('Location', 1.8319233785552127), ('Load-shedding', 5.04036943535694), ('Financial Condition', 15.811768226878392), ('Internet Type', 4.52156613998774), ('Network Type', 6.835637091613191), ('Class Duration', 18.31453805887427), ('Self Lms', 6.05124517287592), ('Device', 2.7112030807521106)]


In [15]:
sample=pd.DataFrame()

sample["Column"]=data.columns[0:-1]
sample["Imp value"]=Dt.feature_importances_*100

sample.sort_values("Imp value",ascending=False)

Column  Imp value
10       Class Duration  18.314538
7   Financial Condition  15.811768
1                   Age  14.387004
3      Institution Type   7.506363
9          Network Type   6.835637
11             Self Lms   6.051245
2       Education Level   6.041567
0                Gender   5.748109
4            IT Student   5.198706
6         Load-shedding   5.040369
8         Internet Type   4.521566
12               Device   2.711203
5              Location   1.831923

In [16]:
from sklearn import tree
with open(r"covidtree.text","w")as f:
    
    f=tree.export_graphviz(Dt,feature_names=data.columns[0:-1],out_file=f)
    
    

In [17]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
Dt=DecisionTreeClassifier(criterion="gini",splitter="best",random_state=10)
knn=KNeighborsClassifier(n_neighbors=int(np.sqrt(len(X_train_res))),metric="euclidean")
svm=SVC(kernel="rbf",gamma=0.1,C=1)
logreg=LogisticRegression(random_state=10)

In [18]:
models= [Dt, knn, svm, logreg]

 

from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
 
for model in models:
    model.fit(X_train_res, Y_train_res)
    Y_pred= model.predict(X_test)
    accuracy= accuracy_score(Y_test, Y_pred) 
    clf_report= classification_report(Y_test, Y_pred) 
    print(confusion_matrix(Y_test,Y_pred))
    print("The accuracy of the ",type(model).__name__, " model is ", accuracy*100 )
    print("Classification report:\n", clf_report)
    print("\n")

[[ 79   2   4]
 [  3 124  10]
 [  0   0  19]]
The accuracy of the  DecisionTreeClassifier  model is  92.11618257261411
Classification report:
               precision    recall  f1-score   support

           0       0.96      0.93      0.95        85
           1       0.98      0.91      0.94       137
           2       0.58      1.00      0.73        19

    accuracy                           0.92       241
   macro avg       0.84      0.94      0.87       241
weighted avg       0.94      0.92      0.93       241



[[56 21  8]
 [30 92 15]
 [ 1  3 15]]
The accuracy of the  KNeighborsClassifier  model is  67.63485477178423
Classification report:
               precision    recall  f1-score   support

           0       0.64      0.66      0.65        85
           1       0.79      0.67      0.73       137
           2       0.39      0.79      0.53        19

    accuracy                           0.68       241
   macro avg       0.61      0.71      0.63       241
weighted avg    

 # Hyperparameter tuning in Decision Tree

In [19]:
from sklearn.model_selection import GridSearchCV
parameter_space = {"min_samples_leaf":[3,5,7,9],
                    "min_samples_split":[3,7,9,11],
                   "max_depth":[12,10,15],
                  "max_features":[0.6,0.7,0.8,0.9,1],
                  "max_leaf_nodes":[100,150,200,250]}
    
    
clf = GridSearchCV(Dt,parameter_space,n_jobs=-1, cv=5)
clf.fit(X_train_res,Y_train_res)

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(random_state=10), n_jobs=-1,
             param_grid={'max_depth': [12, 10, 15],
                         'max_features': [0.6, 0.7, 0.8, 0.9, 1],
                         'max_leaf_nodes': [100, 150, 200, 250],
                         'min_samples_leaf': [3, 5, 7, 9],
                         'min_samples_split': [3, 7, 9, 11]})

In [20]:
clf.best_params_

{'max_depth': 15,
 'max_features': 0.7,
 'max_leaf_nodes': 150,
 'min_samples_leaf': 3,
 'min_samples_split': 3}

In [21]:
clf.best_score_

0.8511150591425499

In [22]:
Dt=DecisionTreeClassifier(criterion="gini",random_state=10,splitter="best",max_depth=12,
                        max_features=0.8,max_leaf_nodes=100,min_samples_leaf=3,min_samples_split=9
                        )
# fit the model 
Dt.fit(X_train_res,Y_train_res)
Y_pred=Dt.predict(X_test)

In [23]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
cfmdt=confusion_matrix(Y_test,Y_pred)
print("Confusion matrix by Decision Tree :")
print(cfmdt)
class_rdt=classification_report(Y_test,Y_pred)
print("Classfication rep by Decision Tree:")
print(class_rdt)
acc_sdt=accuracy_score(Y_test,Y_pred)
print("Accuracy score by Decision Tree:",acc_sdt)

Confusion matrix by Decision Tree :
[[ 70   8   7]
 [ 15 105  17]
 [  0   3  16]]
Classfication rep by Decision Tree:
              precision    recall  f1-score   support

           0       0.82      0.82      0.82        85
           1       0.91      0.77      0.83       137
           2       0.40      0.84      0.54        19

    accuracy                           0.79       241
   macro avg       0.71      0.81      0.73       241
weighted avg       0.84      0.79      0.81       241

Accuracy score by Decision Tree: 0.7925311203319502


# Hyperparameter tuning in Knn

In [24]:
np.sqrt(len(X_train_res))

38.262252939417984

In [25]:
knn=KNeighborsClassifier(n_neighbors=42,metric="euclidean")
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score


In [26]:
knn.fit(X_train_res,Y_train_res)
Y_pred=knn.predict(X_test)
cm=confusion_matrix(Y_test,Y_pred)
print("Confusion matrix by KNN :\n",cm)
class_r=classification_report(Y_test,Y_pred)
print("Classfication rep by KNN :")
print(class_r)
acc_s=accuracy_score(Y_test,Y_pred)
print("Accuracy score by  KNN :",acc_s)

Confusion matrix by KNN :
 [[61 15  9]
 [38 87 12]
 [ 1  3 15]]
Classfication rep by KNN :
              precision    recall  f1-score   support

           0       0.61      0.72      0.66        85
           1       0.83      0.64      0.72       137
           2       0.42      0.79      0.55        19

    accuracy                           0.68       241
   macro avg       0.62      0.71      0.64       241
weighted avg       0.72      0.68      0.68       241

Accuracy score by  KNN : 0.6763485477178424


In [27]:
my_dict={}
for K in range(3,42):
    knn=KNeighborsClassifier(n_neighbors=K,metric="euclidean")
    knn.fit(X_train_res,Y_train_res)
    Y_pred=knn.predict(X_test)
    print ("Accuracy is ", accuracy_score(Y_test,Y_pred), "for K-Value:",K)
    my_dict[K]=accuracy_score(Y_test,Y_pred)


Accuracy is  0.8547717842323651 for K-Value: 3
Accuracy is  0.8755186721991701 for K-Value: 4
Accuracy is  0.8630705394190872 for K-Value: 5
Accuracy is  0.8381742738589212 for K-Value: 6
Accuracy is  0.8091286307053942 for K-Value: 7
Accuracy is  0.8215767634854771 for K-Value: 8
Accuracy is  0.8132780082987552 for K-Value: 9
Accuracy is  0.7759336099585062 for K-Value: 10
Accuracy is  0.7800829875518672 for K-Value: 11
Accuracy is  0.7676348547717843 for K-Value: 12
Accuracy is  0.7676348547717843 for K-Value: 13
Accuracy is  0.7634854771784232 for K-Value: 14
Accuracy is  0.7385892116182573 for K-Value: 15
Accuracy is  0.7302904564315352 for K-Value: 16
Accuracy is  0.7261410788381742 for K-Value: 17
Accuracy is  0.7302904564315352 for K-Value: 18
Accuracy is  0.7302904564315352 for K-Value: 19
Accuracy is  0.7385892116182573 for K-Value: 20
Accuracy is  0.7344398340248963 for K-Value: 21
Accuracy is  0.7302904564315352 for K-Value: 22
Accuracy is  0.7261410788381742 for K-Value: 23

In [28]:
for i in my_dict:
    if my_dict[i]==max(my_dict.values()):
        print(i,":",my_dict[i])

4 : 0.8755186721991701


# Hyperparameter tuning in SVC

In [63]:
from sklearn.svm import SVC
K=np.arange(10,100,10)

my_dict={}
for K in np.arange(10,100,10):
    svm=SVC(kernel="rbf",gamma=0.1,C=K)
    svm.fit(X_train_res,Y_train_res)
    Y_pred=svm.predict(X_test)
    print ("Accuracy is ", accuracy_score(Y_test,Y_pred), "for K-Value:",K)
    my_dict[K]=accuracy_score(Y_test,Y_pred)


Accuracy is  0.9087136929460581 for K-Value: 10
Accuracy is  0.9128630705394191 for K-Value: 20
Accuracy is  0.9128630705394191 for K-Value: 30
Accuracy is  0.9128630705394191 for K-Value: 40
Accuracy is  0.9128630705394191 for K-Value: 50
Accuracy is  0.9128630705394191 for K-Value: 60
Accuracy is  0.9128630705394191 for K-Value: 70
Accuracy is  0.9128630705394191 for K-Value: 80
Accuracy is  0.9128630705394191 for K-Value: 90


In [64]:
for i in my_dict:
    if my_dict[i]==max(my_dict.values()):
        print(i,":",my_dict[i])

20 : 0.9128630705394191
30 : 0.9128630705394191
40 : 0.9128630705394191
50 : 0.9128630705394191
60 : 0.9128630705394191
70 : 0.9128630705394191
80 : 0.9128630705394191
90 : 0.9128630705394191


In [65]:
for i in my_dict:
    if my_dict[i]==max(my_dict.values()):
        print(i,":",my_dict[i])

20 : 0.9128630705394191
30 : 0.9128630705394191
40 : 0.9128630705394191
50 : 0.9128630705394191
60 : 0.9128630705394191
70 : 0.9128630705394191
80 : 0.9128630705394191
90 : 0.9128630705394191


In [66]:
from sklearn.svm import SVC
K=np.arange(10,100,10)

my_dict={}
for K in np.arange(10,100,10):
    svm=SVC(kernel="rbf",gamma=0.01,C=K)
    svm.fit(X_train_res,Y_train_res)
    Y_pred=svm.predict(X_test)
    print ("Accuracy is ", accuracy_score(Y_test,Y_pred), "for K-Value:",K)
    my_dict[K]=accuracy_score(Y_test,Y_pred)


Accuracy is  0.7012448132780082 for K-Value: 10
Accuracy is  0.7302904564315352 for K-Value: 20
Accuracy is  0.7676348547717843 for K-Value: 30
Accuracy is  0.7593360995850622 for K-Value: 40
Accuracy is  0.7510373443983402 for K-Value: 50
Accuracy is  0.7759336099585062 for K-Value: 60
Accuracy is  0.7883817427385892 for K-Value: 70
Accuracy is  0.7966804979253111 for K-Value: 80
Accuracy is  0.8008298755186722 for K-Value: 90


In [67]:
for i in my_dict:
    if my_dict[i]==max(my_dict.values()):
        print(i,":",my_dict[i])

90 : 0.8008298755186722


In [68]:
svm=SVC(kernel="rbf",gamma=0.01,C=20)
svm.fit(X_train_res,Y_train_res)
Y_pred=svm.predict(X_test)

cm=confusion_matrix(Y_test,Y_pred)
print("Confusion matrix by SVC :\n",cm)
class_r=classification_report(Y_test,Y_pred)
print("Classfication rep by SVC :")
print(class_r)
acc_s=accuracy_score(Y_test,Y_pred)
print("Accuracy score by  SVC :",acc_s)

Confusion matrix by SVC :
 [[ 58  22   5]
 [ 14 102  21]
 [  1   2  16]]
Classfication rep by SVC :
              precision    recall  f1-score   support

           0       0.79      0.68      0.73        85
           1       0.81      0.74      0.78       137
           2       0.38      0.84      0.52        19

    accuracy                           0.73       241
   macro avg       0.66      0.76      0.68       241
weighted avg       0.77      0.73      0.74       241

Accuracy score by  SVC : 0.7302904564315352


In [69]:
from sklearn.ensemble import RandomForestClassifier,ExtraTreesClassifier,AdaBoostClassifier,GradientBoostingClassifier
from xgboost import XGBClassifier
Rf=RandomForestClassifier(n_estimators=500,random_state=10,bootstrap=True,n_jobs=-1) 
Et=ExtraTreesClassifier(random_state=10, bootstrap=True)
Adboost=AdaBoostClassifier(base_estimator=DecisionTreeClassifier(random_state=10),n_estimators=100,random_state=10)
grad_boost=GradientBoostingClassifier(n_estimators=300,random_state=10)
Xg_boost=XGBClassifier(n_estimators=300,random_state=10)



In [70]:
models=[Rf,Et,Adboost,grad_boost,Xg_boost]
for model in models:
    model.fit(X_train_res, Y_train_res)
    Y_pred= model.predict(X_test)
    accuracy= accuracy_score(Y_test, Y_pred) 
    clf_report= classification_report(Y_test, Y_pred) 
    print(confusion_matrix(Y_test,Y_pred))
    print("The accuracy of the ",type(model).__name__, " model is ", accuracy*100 )
    print("Classification report:\n", clf_report)
    print("\n")

[[ 79   2   4]
 [  3 124  10]
 [  0   0  19]]
The accuracy of the  RandomForestClassifier  model is  92.11618257261411
Classification report:
               precision    recall  f1-score   support

           0       0.96      0.93      0.95        85
           1       0.98      0.91      0.94       137
           2       0.58      1.00      0.73        19

    accuracy                           0.92       241
   macro avg       0.84      0.94      0.87       241
weighted avg       0.94      0.92      0.93       241



[[ 79   2   4]
 [  3 124  10]
 [  0   0  19]]
The accuracy of the  ExtraTreesClassifier  model is  92.11618257261411
Classification report:
               precision    recall  f1-score   support

           0       0.96      0.93      0.95        85
           1       0.98      0.91      0.94       137
           2       0.58      1.00      0.73        19

    accuracy                           0.92       241
   macro avg       0.84      0.94      0.87       241
weighte

In [36]:
from sklearn.model_selection import GridSearchCV
parameter_space = {
    
                   "n_estimators":[50,100,200,300,400,500]}
    
clf = GridSearchCV(Et,parameter_space,n_jobs=-1, cv=5)
clf.fit(X_train_res,Y_train_res)
clf.best_params_

{'n_estimators': 200}

In [37]:
clf.best_score_


0.8955093739772781

In [38]:
Et=ExtraTreesClassifier(n_estimators=100,random_state=10,bootstrap=True)
Et.fit(X_train_res,Y_train_res)
Y_pred=Et.predict(X_test)
cm=confusion_matrix(Y_test,Y_pred)
print("Confusion matrix by Extra Trees Classifier:\n",cm)
class_r=classification_report(Y_test,Y_pred)
print("Classfication rep by Extra Trees Classifier:")
print(class_r)
acc_s=accuracy_score(Y_test,Y_pred)
print("Accuracy score by  Extra Trees Classifier:",acc_s)

Confusion matrix by Extra Trees Classifier:
 [[ 79   2   4]
 [  3 124  10]
 [  0   0  19]]
Classfication rep by Extra Trees Classifier:
              precision    recall  f1-score   support

           0       0.96      0.93      0.95        85
           1       0.98      0.91      0.94       137
           2       0.58      1.00      0.73        19

    accuracy                           0.92       241
   macro avg       0.84      0.94      0.87       241
weighted avg       0.94      0.92      0.93       241

Accuracy score by  Extra Trees Classifier: 0.921161825726141


In [39]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier
from sklearn.neighbors import KNeighborsClassifier
# create the sub models
estimators = []
model1 = LogisticRegression()
estimators.append(('log', model1))
model2 = DecisionTreeClassifier(criterion='gini',random_state=10)
estimators.append(('tree', model2))
model3 = SVC(kernel="rbf", C=90,gamma=0.1)
estimators.append(('svm', model3))
model4 = KNeighborsClassifier(n_neighbors=15, metric='euclidean')
estimators.append(('knn', model4))
print(estimators)
# create the ensemble model
ensemble = VotingClassifier(estimators)
ensemble.fit(X_train_res,Y_train_res)
Y_pred=ensemble.predict(X_test)
#print(Y_pred)

[('log', LogisticRegression()), ('tree', DecisionTreeClassifier(random_state=10)), ('svm', SVC(C=90, gamma=0.1)), ('knn', KNeighborsClassifier(metric='euclidean', n_neighbors=15))]


In [40]:
cm=confusion_matrix(Y_test,Y_pred)
print("Confusion matrix by Voting Classifier:\n",cm)
class_r=classification_report(Y_test,Y_pred)
print("Classfication rep by Voting Classifier:")
print(class_r)
acc_s=accuracy_score(Y_test,Y_pred)
print("Accuracy score by  Voting Classifier:",acc_s)

Confusion matrix by Voting Classifier:
 [[ 79   3   3]
 [ 13 118   6]
 [  0   1  18]]
Classfication rep by Voting Classifier:
              precision    recall  f1-score   support

           0       0.86      0.93      0.89        85
           1       0.97      0.86      0.91       137
           2       0.67      0.95      0.78        19

    accuracy                           0.89       241
   macro avg       0.83      0.91      0.86       241
weighted avg       0.91      0.89      0.89       241

Accuracy score by  Voting Classifier: 0.8921161825726142


In [41]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import StackingClassifier
from sklearn.neighbors import KNeighborsClassifier
# create the sub models
level0 = []
model1 = LogisticRegression()
level0.append(('log', model1))
model2 = DecisionTreeClassifier(criterion='gini',random_state=10)
level0.append(('tree', model2))
model3 = SVC(kernel="rbf", C=90,gamma=0.1)
#level0.append(('svm', model3))
model4 = KNeighborsClassifier(n_neighbors=5, metric='euclidean')
level0.append(('knn', model4))
print(estimators)
level1=LogisticRegression()
# create the ensemble model
ensemble = StackingClassifier(estimators=level0, final_estimator=level1, cv=5,passthrough=False)
ensemble.fit(X_train_res,Y_train_res)
Y_pred=ensemble.predict(X_test)
#print(Y_pred)

[('log', LogisticRegression()), ('tree', DecisionTreeClassifier(random_state=10)), ('svm', SVC(C=90, gamma=0.1)), ('knn', KNeighborsClassifier(metric='euclidean', n_neighbors=15))]


In [42]:
cm=confusion_matrix(Y_test,Y_pred)
print("Confusion matrix by Stacking Classifier:\n",cm)
class_r=classification_report(Y_test,Y_pred)
print("Classfication rep by Stacking Classifier:")
print(class_r)
acc_s=accuracy_score(Y_test,Y_pred)
print("Accuracy score by  Stacking Classifier:",acc_s)

Confusion matrix by Stacking Classifier:
 [[ 79   2   4]
 [  3 121  13]
 [  0   0  19]]
Classfication rep by Stacking Classifier:
              precision    recall  f1-score   support

           0       0.96      0.93      0.95        85
           1       0.98      0.88      0.93       137
           2       0.53      1.00      0.69        19

    accuracy                           0.91       241
   macro avg       0.82      0.94      0.86       241
weighted avg       0.94      0.91      0.92       241

Accuracy score by  Stacking Classifier: 0.9087136929460581


In [43]:
from xgboost import XGBClassifier
Xg=XGBClassifier(random_state=10,max_depth=10,max_leaves=10)
Xg.fit(X_train_res,Y_train_res)
Y_pred=Xg.predict(X_test)

In [44]:
from sklearn.model_selection import GridSearchCV
parameter_space = {"n_estimators":[100,200,300,400],
                   "max_depth":[12,10,15],
                  "max_leaves":[5,10,15,20]}
    
    
clf = GridSearchCV(Xg,parameter_space,n_jobs=-1, cv=5)
clf.fit(X_train_res,Y_train_res)

GridSearchCV(cv=5,
             estimator=XGBClassifier(base_score=None, booster=None,
                                     callbacks=None, colsample_bylevel=None,
                                     colsample_bynode=None,
                                     colsample_bytree=None,
                                     early_stopping_rounds=None,
                                     enable_categorical=False, eval_metric=None,
                                     feature_types=None, gamma=None,
                                     gpu_id=None, grow_policy=None,
                                     importance_type=None,
                                     interaction_constraints=None,
                                     learning_rate=None,...
                                     max_cat_threshold=None,
                                     max_cat_to_onehot=None,
                                     max_delta_step=None, max_depth=10,
                                     max_leaves=10, m

In [45]:
clf.best_params_

{'max_depth': 12, 'max_leaves': 5, 'n_estimators': 100}

In [71]:
from xgboost import XGBClassifier
Xg=XGBClassifier(n_estimators=100,random_state=10,max_depth=12,max_leaves=5)
Xg.fit(X_train_res,Y_train_res)
Y_pred=Xg.predict(X_test)
cm=confusion_matrix(Y_test,Y_pred)
print("Confusion matrix by XGB Classifier:\n",cm)
class_r=classification_report(Y_test,Y_pred)
print("Classfication rep by XGB Classifier:")
print(class_r)
acc_s=accuracy_score(Y_test,Y_pred)
print("Accuracy score by  XGB Classifier:",acc_s)

Confusion matrix by XGB Classifier:
 [[ 79   2   4]
 [  2 125  10]
 [  0   0  19]]
Classfication rep by XGB Classifier:
              precision    recall  f1-score   support

           0       0.98      0.93      0.95        85
           1       0.98      0.91      0.95       137
           2       0.58      1.00      0.73        19

    accuracy                           0.93       241
   macro avg       0.85      0.95      0.88       241
weighted avg       0.95      0.93      0.93       241

Accuracy score by  XGB Classifier: 0.9253112033195021


In [47]:
sample.sort_values("Imp value",ascending=False)

Column  Imp value
10       Class Duration  18.314538
7   Financial Condition  15.811768
1                   Age  14.387004
3      Institution Type   7.506363
9          Network Type   6.835637
11             Self Lms   6.051245
2       Education Level   6.041567
0                Gender   5.748109
4            IT Student   5.198706
6         Load-shedding   5.040369
8         Internet Type   4.521566
12               Device   2.711203
5              Location   1.831923

In [48]:
from lazypredict.Supervised import LazyClassifier
clf=LazyClassifier(ignore_warnings=True,verbose=0,custom_metric=None)
models,predictions=clf.fit(X_train_res,X_test,Y_train_res,Y_test)

100%|██████████████████████████████████████████████████████████████████████████████████| 29/29 [00:02<00:00, 13.27it/s]


In [49]:
accuracy=pd.DataFrame(models)

In [50]:
accuracy

Accuracy  Balanced Accuracy ROC AUC  F1 Score  \
Model                                                                          
XGBClassifier                      0.93               0.95    None      0.93   
DecisionTreeClassifier             0.92               0.94    None      0.93   
ExtraTreesClassifier               0.92               0.94    None      0.93   
RandomForestClassifier             0.92               0.94    None      0.93   
LGBMClassifier                     0.92               0.94    None      0.92   
LabelPropagation                   0.91               0.94    None      0.92   
LabelSpreading                     0.91               0.94    None      0.92   
BaggingClassifier                  0.92               0.93    None      0.92   
ExtraTreeClassifier                0.92               0.93    None      0.92   
KNeighborsClassifier               0.85               0.88    None      0.86   
SVC                                0.76               0.78    None      0.77   
NuSVC                              0.74               0.77    None      0.75   
RidgeClassifier                    0.68               0.72    None      0.69   
LinearSVC                          0.68               0.72    None      0.69   
LinearDiscriminantAnalysis         0.68               0.72    None      0.69   
CalibratedClassifierCV             0.68               0.72    None      0.69   
RidgeClassifierCV                  0.68               0.71    None      0.68   
QuadraticDiscriminantAnalysis      0.72               0.71    None      0.73   
SGDClassifier                      0.62               0.70    None      0.63   
LogisticRegression                 0.67               0.69    None      0.67   
AdaBoostClassifier                 0.62               0.68    None      0.64   
GaussianNB                         0.59               0.66    None      0.61   
NearestCentroid                    0.59               0.64    None      0.61   
BernoulliNB                        0.60               0.63    None      0.61   
Perceptron                         0.65               0.63    None      0.65   
PassiveAggressiveClassifier        0.51               0.60    None      0.56   
DummyClassifier                    0.35               0.33    None      0.18   

                               Time Taken  
Model                                      
XGBClassifier                        0.28  
DecisionTreeClassifier               0.02  
ExtraTreesClassifier                 0.14  
RandomForestClassifier               0.16  
LGBMClassifier                       0.20  
LabelPropagation                     0.09  
LabelSpreading                       0.14  
BaggingClassifier                    0.03  
ExtraTreeClassifier                  0.03  
KNeighborsClassifier                 0.03  
SVC                                  0.05  
NuSVC                                0.11  
RidgeClassifier                      0.02  
LinearSVC                            0.13  
LinearDiscriminantAnalysis           0.02  
CalibratedClassifierCV               0.55  
RidgeClassifierCV                    0.00  
QuadraticDiscriminantAnalysis        0.02  
SGDClassifier                        0.03  
LogisticRegression                   0.03  
AdaBoostClassifier                   0.09  
GaussianNB                           0.00  
NearestCentroid                      0.00  
BernoulliNB                          0.00  
Perceptron                           0.00  
PassiveAggressiveClassifier          0.02  
DummyClassifier                      0.00

In [51]:
new_data = data[["Class Duration","Financial Condition","Age","Institution Type","Network Type","Self Lms","Education Level","Adaptivity Level"]]

In [52]:
new_data

Class Duration  Financial Condition  Age  Institution Type  \
0                  2                    0    3                 1   
1                  1                    0    3                 1   
2                  1                    0    2                 0   
3                  1                    0    1                 1   
4                  0                    1    2                 1   
...              ...                  ...  ...               ...   
1200               1                    0    2                 1   
1201               2                    0    2                 1   
1202               1                    0    1                 1   
1203               1                    0    2                 1   
1204               1                    1    1                 1   

      Network Type  Self Lms  Education Level  Adaptivity Level  
0                2         0                2                 1  
1                2         1                2                 1  
2                2         0                0                 1  
3                2         0                1                 1  
4                1         0                1                 0  
...            ...       ...              ...               ...  
1200             2         0                0                 0  
1201             2         0                0                 1  
1202             1         0                1                 1  
1203             2         0                0                 0  
1204             1         0                1                 1  

[1205 rows x 8 columns]

# Applying PCA

In [59]:
from sklearn.decomposition import PCA
pca = PCA(n_components=0.90) #to view the entire eigen vector, no subsetting
X_train_new = pca.fit_transform(X_train_res)
X_test_new = pca.transform(X_test)
explained_variance = pca.explained_variance_ratio_
print(explained_variance)

[0.23758579 0.13398173 0.10681876 0.1017416  0.07391902 0.06778557
 0.05823499 0.04716601 0.04311094 0.03873826]


In [60]:
pca.n_components_

10

In [62]:
0.23758579 + 0.13398173 + 0.10681876 + 0.1017416 + 0.07391902 + 0.06778557 + 0.05823499 + 0.04716601 + 0.04311094 + 0.03873826

0.90908267

In [73]:
from sklearn.svm import SVC
classifier = XGBClassifier(n_estimators=100,random_state=10,max_depth=12,max_leaves=5)
classifier.fit(X_train_new, Y_train_res)
Y_pred = classifier.predict(X_test_new)


from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm = confusion_matrix(Y_test,Y_pred)
print("cfm :",cfm)
print()
print("Classification report :")
print(classification_report(Y_test, Y_pred))

acc = accuracy_score(Y_test, Y_pred)
print("Accuracy of the model :",acc)

cfm : [[ 79   2   4]
 [  3 124  10]
 [  0   1  18]]

Classification report :
              precision    recall  f1-score   support

           0       0.96      0.93      0.95        85
           1       0.98      0.91      0.94       137
           2       0.56      0.95      0.71        19

    accuracy                           0.92       241
   macro avg       0.83      0.93      0.86       241
weighted avg       0.94      0.92      0.92       241

Accuracy of the model : 0.91701244813278
