# Student Adaptivity Analysis

# To get an idea about the effectiveness of online education

## During the Covid-19 phase everything went on the online platform even the education system. Students whole education was completely on the online mode. This project shows how the students were able to adapt the online mode of education based on several factors taken into consideration. So the outcome is Prediction of Students Adaptivity Level in Online Education using Machine Learning Model

In [1]:
import pandas as pd 
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import DecisionTreeClassifier

In [2]:
data=pd.read_csv(r"C:\Users\Jay Rathod\Downloads\Student_Adaptivity_preProcessed.csv")

In [3]:
data.head()

Gender  Age  Education Level  Institution Type  IT Student  Location  \
0       0    3                2                 1           0         1   
1       1    3                2                 1           0         1   
2       1    2                0                 0           0         1   
3       1    1                1                 1           0         1   
4       1    2                1                 1           0         1   

   Load-shedding  Financial Condition  Internet Type  Network Type  \
0              1                    0              1             2   
1              0                    0              0             2   
2              1                    0              1             2   
3              1                    0              0             2   
4              1                    1              0             1   

   Class Duration  Self Lms  Device  Adaptivity Level  
0               2         0       2                 1  
1               1         1       1                 1  
2               1         0       1                 1  
3               1         0       1                 1  
4               0         0       1                 0

In [4]:
data.shape

(1205, 14)

In [5]:
data.dtypes

Gender                 int64
Age                    int64
Education Level        int64
Institution Type       int64
IT Student             int64
Location               int64
Load-shedding          int64
Financial Condition    int64
Internet Type          int64
Network Type           int64
Class Duration         int64
Self Lms               int64
Device                 int64
Adaptivity Level       int64
dtype: object

In [6]:
data.isnull().sum()

Gender                 0
Age                    0
Education Level        0
Institution Type       0
IT Student             0
Location               0
Load-shedding          0
Financial Condition    0
Internet Type          0
Network Type           0
Class Duration         0
Self Lms               0
Device                 0
Adaptivity Level       0
dtype: int64

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1205 entries, 0 to 1204
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Gender               1205 non-null   int64
 1   Age                  1205 non-null   int64
 2   Education Level      1205 non-null   int64
 3   Institution Type     1205 non-null   int64
 4   IT Student           1205 non-null   int64
 5   Location             1205 non-null   int64
 6   Load-shedding        1205 non-null   int64
 7   Financial Condition  1205 non-null   int64
 8   Internet Type        1205 non-null   int64
 9   Network Type         1205 non-null   int64
 10  Class Duration       1205 non-null   int64
 11  Self Lms             1205 non-null   int64
 12  Device               1205 non-null   int64
 13  Adaptivity Level     1205 non-null   int64
dtypes: int64(14)
memory usage: 131.9 KB


In [8]:
data.describe(include="all").T

count      mean       std  min  25%  50%  75%  max
Gender               1205.0  0.449793  0.497679  0.0  0.0  0.0  1.0  1.0
Age                  1205.0  2.122822  1.210359  0.0  1.0  2.0  3.0  5.0
Education Level      1205.0  1.196680  0.722437  0.0  1.0  1.0  2.0  2.0
Institution Type     1205.0  0.682988  0.465506  0.0  0.0  1.0  1.0  1.0
IT Student           1205.0  0.252282  0.434503  0.0  0.0  0.0  1.0  1.0
Location             1205.0  0.775934  0.417139  0.0  1.0  1.0  1.0  1.0
Load-shedding        1205.0  0.833195  0.372956  0.0  1.0  1.0  1.0  1.0
Financial Condition  1205.0  0.341909  0.605302  0.0  0.0  0.0  1.0  2.0
Internet Type        1205.0  0.423237  0.494277  0.0  0.0  0.0  1.0  1.0
Network Type         1205.0  1.627386  0.515295  0.0  1.0  2.0  2.0  2.0
Class Duration       1205.0  1.047303  0.548559  0.0  1.0  1.0  1.0  2.0
Self Lms             1205.0  0.174274  0.379502  0.0  0.0  0.0  0.0  1.0
Device               1205.0  0.890456  0.384003  0.0  1.0  1.0  1.0  2.0
Adaptivity Level     1205.0  0.684647  0.618221  0.0  0.0  1.0  1.0  2.0

In [9]:
data.isnull().sum()

Gender                 0
Age                    0
Education Level        0
Institution Type       0
IT Student             0
Location               0
Load-shedding          0
Financial Condition    0
Internet Type          0
Network Type           0
Class Duration         0
Self Lms               0
Device                 0
Adaptivity Level       0
dtype: int64

In [10]:
le=LabelEncoder()
for i in data.columns:
    if data[i].dtype=="object" or data[i].dtype=="object":
        data[i]=le.fit_transform(data[i])

In [11]:
data

Gender  Age  Education Level  Institution Type  IT Student  Location  \
0          0    3                2                 1           0         1   
1          1    3                2                 1           0         1   
2          1    2                0                 0           0         1   
3          1    1                1                 1           0         1   
4          1    2                1                 1           0         1   
...      ...  ...              ...               ...         ...       ...   
1200       1    2                0                 1           0         1   
1201       1    2                0                 1           0         0   
1202       0    1                1                 1           0         1   
1203       1    2                0                 1           0         0   
1204       1    1                1                 1           0         1   

      Load-shedding  Financial Condition  Internet Type  Network Type  \
0                 1                    0              1             2   
1                 0                    0              0             2   
2                 1                    0              1             2   
3                 1                    0              0             2   
4                 1                    1              0             1   
...             ...                  ...            ...           ...   
1200              1                    0              1             2   
1201              0                    0              1             2   
1202              1                    0              0             1   
1203              1                    0              1             2   
1204              1                    1              0             1   

      Class Duration  Self Lms  Device  Adaptivity Level  
0                  2         0       2                 1  
1                  1         1       1                 1  
2                  1         0       1                 1  
3                  1         0       1                 1  
4                  0         0       1                 0  
...              ...       ...     ...               ...  
1200               1         0       1                 0  
1201               2         0       1                 1  
1202               1         0       1                 1  
1203               1         0       1                 0  
1204               1         0       1                 1  

[1205 rows x 14 columns]

In [12]:
data.columns

Index(['Gender', 'Age', 'Education Level', 'Institution Type', 'IT Student',
       'Location', 'Load-shedding', 'Financial Condition', 'Internet Type',
       'Network Type', 'Class Duration', 'Self Lms', 'Device',
       'Adaptivity Level'],
      dtype='object')

In [13]:
data

Gender  Age  Education Level  Institution Type  IT Student  Location  \
0          0    3                2                 1           0         1   
1          1    3                2                 1           0         1   
2          1    2                0                 0           0         1   
3          1    1                1                 1           0         1   
4          1    2                1                 1           0         1   
...      ...  ...              ...               ...         ...       ...   
1200       1    2                0                 1           0         1   
1201       1    2                0                 1           0         0   
1202       0    1                1                 1           0         1   
1203       1    2                0                 1           0         0   
1204       1    1                1                 1           0         1   

      Load-shedding  Financial Condition  Internet Type  Network Type  \
0                 1                    0              1             2   
1                 0                    0              0             2   
2                 1                    0              1             2   
3                 1                    0              0             2   
4                 1                    1              0             1   
...             ...                  ...            ...           ...   
1200              1                    0              1             2   
1201              0                    0              1             2   
1202              1                    0              0             1   
1203              1                    0              1             2   
1204              1                    1              0             1   

      Class Duration  Self Lms  Device  Adaptivity Level  
0                  2         0       2                 1  
1                  1         1       1                 1  
2                  1         0       1                 1  
3                  1         0       1                 1  
4                  0         0       1                 0  
...              ...       ...     ...               ...  
1200               1         0       1                 0  
1201               2         0       1                 1  
1202               1         0       1                 1  
1203               1         0       1                 0  
1204               1         0       1                 1  

[1205 rows x 14 columns]

In [14]:
X=data.values[:,:-1]
Y=data.values[:,-1]

In [15]:
scaler=StandardScaler()

In [16]:
X=scaler.fit_transform(X)

In [17]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,random_state=10,test_size=0.2)

In [18]:
print(X_train.shape,X_test.shape,Y_train.shape,Y_test.shape)

(964, 13) (241, 13) (964,) (241,)


In [19]:
Dt=DecisionTreeClassifier(criterion="gini",random_state=10,splitter="best")
# fit the model 
Dt.fit(X_train,Y_train)
Y_pred=Dt.predict(X_test)

In [20]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
cm=confusion_matrix(Y_test,Y_pred)
print("Confusion matrix by Decision Tree :\n",cm)
class_r=classification_report(Y_test,Y_pred)
print("Classfication rep by Decision Tree :")
print(class_r)
acc_s=accuracy_score(Y_test,Y_pred)
print("Accuracy score by  Decision Tree :",acc_s)

Confusion matrix by Decision Tree :
 [[ 79   3   3]
 [  3 134   0]
 [  0   2  17]]
Classfication rep by Decision Tree :
              precision    recall  f1-score   support

           0       0.96      0.93      0.95        85
           1       0.96      0.98      0.97       137
           2       0.85      0.89      0.87        19

    accuracy                           0.95       241
   macro avg       0.93      0.93      0.93       241
weighted avg       0.95      0.95      0.95       241

Accuracy score by  Decision Tree : 0.9543568464730291


In [21]:
Dt.score(X_train,Y_train)

0.9263485477178424

In [22]:
print(list(zip(data.columns[0:-1],Dt.feature_importances_*100)))

[('Gender', 9.111479122967141), ('Age', 12.597797408332866), ('Education Level', 5.109925390462684), ('Institution Type', 3.375307429618242), ('IT Student', 4.145268087864997), ('Location', 5.649609174144579), ('Load-shedding', 7.451100312570002), ('Financial Condition', 7.732046121823739), ('Internet Type', 6.389937420789071), ('Network Type', 6.381140741694962), ('Class Duration', 22.138595829946862), ('Self Lms', 5.656876376159624), ('Device', 4.2609165836252325)]


In [23]:
sample=pd.DataFrame()

sample["Column"]=data.columns[0:-1]
sample["Imp value"]=Dt.feature_importances_*100

sample.sort_values("Imp value",ascending=False)

Column  Imp value
10       Class Duration  22.138596
1                   Age  12.597797
0                Gender   9.111479
7   Financial Condition   7.732046
6         Load-shedding   7.451100
8         Internet Type   6.389937
9          Network Type   6.381141
11             Self Lms   5.656876
5              Location   5.649609
2       Education Level   5.109925
12               Device   4.260917
4            IT Student   4.145268
3      Institution Type   3.375307

In [24]:
from sklearn import tree
with open(r"covidtree.text","w")as f:
    
    f=tree.export_graphviz(Dt,feature_names=data.columns[0:-1],out_file=f)
    
    

In [25]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
Dt=DecisionTreeClassifier(criterion="gini",splitter="best",random_state=10)
knn=KNeighborsClassifier(n_neighbors=int(np.sqrt(len(X_train))),metric="euclidean")
svm=SVC(kernel="rbf",gamma=0.1,C=1)
logreg=LogisticRegression(random_state=10)

In [26]:
models= [Dt, knn, svm, logreg]

 

from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
 
for model in models:
    model.fit(X_train, Y_train)
    Y_pred= model.predict(X_test)
    accuracy= accuracy_score(Y_test, Y_pred) 
    clf_report= classification_report(Y_test, Y_pred) 
    print(confusion_matrix(Y_test,Y_pred))
    print("The accuracy of the ",type(model).__name__, " model is ", accuracy*100 )
    print("Classification report:\n", clf_report)
    print("\n")

[[ 79   3   3]
 [  3 134   0]
 [  0   2  17]]
The accuracy of the  DecisionTreeClassifier  model is  95.4356846473029
Classification report:
               precision    recall  f1-score   support

           0       0.96      0.93      0.95        85
           1       0.96      0.98      0.97       137
           2       0.85      0.89      0.87        19

    accuracy                           0.95       241
   macro avg       0.93      0.93      0.93       241
weighted avg       0.95      0.95      0.95       241



[[ 50  35   0]
 [ 25 112   0]
 [  3   9   7]]
The accuracy of the  KNeighborsClassifier  model is  70.12448132780082
Classification report:
               precision    recall  f1-score   support

           0       0.64      0.59      0.61        85
           1       0.72      0.82      0.76       137
           2       1.00      0.37      0.54        19

    accuracy                           0.70       241
   macro avg       0.79      0.59      0.64       241
weighted

 # Hyperparameter tuning in Decision Tree

In [27]:
from sklearn.model_selection import GridSearchCV
parameter_space = {"min_samples_leaf":[3,5,7,9],
                    "min_samples_split":[3,7,9,11],
                   "max_depth":[12,10,15],
                  "max_features":[0.6,0.7,0.8,0.9,1],
                  "max_leaf_nodes":[100,150,200,250]}
    
    
clf = GridSearchCV(Dt,parameter_space,n_jobs=-1, cv=5)
clf.fit(X_train,Y_train)

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(random_state=10), n_jobs=-1,
             param_grid={'max_depth': [12, 10, 15],
                         'max_features': [0.6, 0.7, 0.8, 0.9, 1],
                         'max_leaf_nodes': [100, 150, 200, 250],
                         'min_samples_leaf': [3, 5, 7, 9],
                         'min_samples_split': [3, 7, 9, 11]})

In [28]:
clf.best_params_

{'max_depth': 10,
 'max_features': 0.9,
 'max_leaf_nodes': 100,
 'min_samples_leaf': 3,
 'min_samples_split': 7}

In [29]:
clf.best_score_

0.7925410189982729

In [30]:
Dt=DecisionTreeClassifier(criterion="gini",random_state=10,splitter="best",max_depth=12,
                        max_features=0.8,max_leaf_nodes=100,min_samples_leaf=3,min_samples_split=9
                        )
# fit the model 
Dt.fit(X_train,Y_train)
Y_pred=Dt.predict(X_test)

In [31]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
cfmdt=confusion_matrix(Y_test,Y_pred)
print("Confusion matrix by Decision Tree :")
print(cfmdt)
class_rdt=classification_report(Y_test,Y_pred)
print("Classfication rep by Decision Tree:")
print(class_rdt)
acc_sdt=accuracy_score(Y_test,Y_pred)
print("Accuracy score by Decision Tree:",acc_sdt)

Confusion matrix by Decision Tree :
[[ 70  11   4]
 [ 24 113   0]
 [  1   7  11]]
Classfication rep by Decision Tree:
              precision    recall  f1-score   support

           0       0.74      0.82      0.78        85
           1       0.86      0.82      0.84       137
           2       0.73      0.58      0.65        19

    accuracy                           0.80       241
   macro avg       0.78      0.74      0.76       241
weighted avg       0.81      0.80      0.80       241

Accuracy score by Decision Tree: 0.8049792531120332


# Hyperparameter tuning in Knn

In [32]:
np.sqrt(len(X_train))

31.04834939252005

In [33]:
knn=KNeighborsClassifier(n_neighbors=42,metric="euclidean")
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score


In [34]:
knn.fit(X_train,Y_train)
Y_pred=knn.predict(X_test)
cm=confusion_matrix(Y_test,Y_pred)
print("Confusion matrix by KNN :\n",cm)
class_r=classification_report(Y_test,Y_pred)
print("Classfication rep by KNN :")
print(class_r)
acc_s=accuracy_score(Y_test,Y_pred)
print("Accuracy score by  KNN :",acc_s)

Confusion matrix by KNN :
 [[ 51  34   0]
 [ 27 110   0]
 [  4  10   5]]
Classfication rep by KNN :
              precision    recall  f1-score   support

           0       0.62      0.60      0.61        85
           1       0.71      0.80      0.76       137
           2       1.00      0.26      0.42        19

    accuracy                           0.69       241
   macro avg       0.78      0.56      0.59       241
weighted avg       0.70      0.69      0.68       241

Accuracy score by  KNN : 0.6887966804979253


In [35]:
my_dict={}
for K in range(3,42):
    knn=KNeighborsClassifier(n_neighbors=K,metric="euclidean")
    knn.fit(X_train,Y_train)
    Y_pred=knn.predict(X_test)
    print ("Accuracy is ", accuracy_score(Y_test,Y_pred), "for K-Value:",K)
    my_dict[K]=accuracy_score(Y_test,Y_pred)


Accuracy is  0.8257261410788381 for K-Value: 3
Accuracy is  0.8589211618257261 for K-Value: 4
Accuracy is  0.8464730290456431 for K-Value: 5
Accuracy is  0.8257261410788381 for K-Value: 6
Accuracy is  0.8174273858921162 for K-Value: 7
Accuracy is  0.8381742738589212 for K-Value: 8
Accuracy is  0.8257261410788381 for K-Value: 9
Accuracy is  0.8008298755186722 for K-Value: 10
Accuracy is  0.8174273858921162 for K-Value: 11
Accuracy is  0.7966804979253111 for K-Value: 12
Accuracy is  0.7883817427385892 for K-Value: 13
Accuracy is  0.7551867219917012 for K-Value: 14
Accuracy is  0.7510373443983402 for K-Value: 15
Accuracy is  0.7510373443983402 for K-Value: 16
Accuracy is  0.7468879668049793 for K-Value: 17
Accuracy is  0.7800829875518672 for K-Value: 18
Accuracy is  0.7676348547717843 for K-Value: 19
Accuracy is  0.7883817427385892 for K-Value: 20
Accuracy is  0.7842323651452282 for K-Value: 21
Accuracy is  0.7717842323651453 for K-Value: 22
Accuracy is  0.7634854771784232 for K-Value: 23

In [36]:
for i in my_dict:
    if my_dict[i]==max(my_dict.values()):
        print(i,":",my_dict[i])

4 : 0.8589211618257261


# Hyperparameter tuning in SVC

In [37]:
from sklearn.svm import SVC
K=np.arange(10,100,10)

my_dict={}
for K in np.arange(10,100,10):
    svm=SVC(kernel="rbf",gamma=0.1,C=K)
    svm.fit(X_train,Y_train)
    Y_pred=svm.predict(X_test)
    print ("Accuracy is ", accuracy_score(Y_test,Y_pred), "for K-Value:",K)
    my_dict[K]=accuracy_score(Y_test,Y_pred)


Accuracy is  0.9585062240663901 for K-Value: 10
Accuracy is  0.9626556016597511 for K-Value: 20
Accuracy is  0.9626556016597511 for K-Value: 30
Accuracy is  0.9626556016597511 for K-Value: 40
Accuracy is  0.9626556016597511 for K-Value: 50
Accuracy is  0.9626556016597511 for K-Value: 60
Accuracy is  0.9626556016597511 for K-Value: 70
Accuracy is  0.9626556016597511 for K-Value: 80
Accuracy is  0.9626556016597511 for K-Value: 90


In [38]:
for i in my_dict:
    if my_dict[i]==max(my_dict.values()):
        print(i,":",my_dict[i])

20 : 0.9626556016597511
30 : 0.9626556016597511
40 : 0.9626556016597511
50 : 0.9626556016597511
60 : 0.9626556016597511
70 : 0.9626556016597511
80 : 0.9626556016597511
90 : 0.9626556016597511


In [39]:
from sklearn.svm import SVC
K=np.arange(10,100,10)

my_dict={}
for K in np.arange(10,100,10):
    svm=SVC(kernel="rbf",gamma=0.01,C=K)
    svm.fit(X_train,Y_train)
    Y_pred=svm.predict(X_test)
    print ("Accuracy is ", accuracy_score(Y_test,Y_pred), "for K-Value:",K)
    my_dict[K]=accuracy_score(Y_test,Y_pred)


Accuracy is  0.7593360995850622 for K-Value: 10
Accuracy is  0.7593360995850622 for K-Value: 20
Accuracy is  0.7717842323651453 for K-Value: 30
Accuracy is  0.8091286307053942 for K-Value: 40
Accuracy is  0.8174273858921162 for K-Value: 50
Accuracy is  0.8215767634854771 for K-Value: 60
Accuracy is  0.8340248962655602 for K-Value: 70
Accuracy is  0.8298755186721992 for K-Value: 80
Accuracy is  0.8464730290456431 for K-Value: 90


In [40]:
for i in my_dict:
    if my_dict[i]==max(my_dict.values()):
        print(i,":",my_dict[i])

90 : 0.8464730290456431


In [41]:
svm=SVC(kernel="rbf",gamma=0.01,C=20)
svm.fit(X_train,Y_train)
Y_pred=svm.predict(X_test)

cm=confusion_matrix(Y_test,Y_pred)
print("Confusion matrix by SVC :\n",cm)
class_r=classification_report(Y_test,Y_pred)
print("Classfication rep by SVC :")
print(class_r)
acc_s=accuracy_score(Y_test,Y_pred)
print("Accuracy score by  SVC :",acc_s)

Confusion matrix by SVC :
 [[ 55  27   3]
 [ 20 116   1]
 [  1   6  12]]
Classfication rep by SVC :
              precision    recall  f1-score   support

           0       0.72      0.65      0.68        85
           1       0.78      0.85      0.81       137
           2       0.75      0.63      0.69        19

    accuracy                           0.76       241
   macro avg       0.75      0.71      0.73       241
weighted avg       0.76      0.76      0.76       241

Accuracy score by  SVC : 0.7593360995850622


In [42]:
from sklearn.ensemble import RandomForestClassifier,ExtraTreesClassifier,AdaBoostClassifier,GradientBoostingClassifier
from xgboost import XGBClassifier
Rf=RandomForestClassifier(n_estimators=500,random_state=10,bootstrap=True,n_jobs=-1) 
Et=ExtraTreesClassifier(random_state=10, bootstrap=True)
Adboost=AdaBoostClassifier(base_estimator=DecisionTreeClassifier(random_state=10),n_estimators=100,random_state=10)
grad_boost=GradientBoostingClassifier(n_estimators=300,random_state=10)
Xg_boost=XGBClassifier(n_estimators=300,random_state=10)



In [43]:
models=[Rf,Et,Adboost,grad_boost,Xg_boost]
for model in models:
    model.fit(X_train, Y_train)
    Y_pred= model.predict(X_test)
    accuracy= accuracy_score(Y_test, Y_pred) 
    clf_report= classification_report(Y_test, Y_pred) 
    print(confusion_matrix(Y_test,Y_pred))
    print("The accuracy of the ",type(model).__name__, " model is ", accuracy*100 )
    print("Classification report:\n", clf_report)
    print("\n")

[[ 79   3   3]
 [  3 134   0]
 [  0   2  17]]
The accuracy of the  RandomForestClassifier  model is  95.4356846473029
Classification report:
               precision    recall  f1-score   support

           0       0.96      0.93      0.95        85
           1       0.96      0.98      0.97       137
           2       0.85      0.89      0.87        19

    accuracy                           0.95       241
   macro avg       0.93      0.93      0.93       241
weighted avg       0.95      0.95      0.95       241



[[ 79   3   3]
 [  3 134   0]
 [  0   1  18]]
The accuracy of the  ExtraTreesClassifier  model is  95.850622406639
Classification report:
               precision    recall  f1-score   support

           0       0.96      0.93      0.95        85
           1       0.97      0.98      0.97       137
           2       0.86      0.95      0.90        19

    accuracy                           0.96       241
   macro avg       0.93      0.95      0.94       241
weighted a

In [44]:
from sklearn.model_selection import GridSearchCV
parameter_space = {
    
                   "n_estimators":[50,100,200,300,400,500]}
    
clf = GridSearchCV(Et,parameter_space,n_jobs=-1, cv=5)
clf.fit(X_train,Y_train)
clf.best_params_

{'n_estimators': 200}

In [45]:
clf.best_score_


0.8640867875647669

In [46]:
Et=ExtraTreesClassifier(n_estimators=100,random_state=10,bootstrap=True)
Et.fit(X_train,Y_train)
Y_pred=Et.predict(X_test)
cm=confusion_matrix(Y_test,Y_pred)
print("Confusion matrix by Extra Trees Classifier:\n",cm)
class_r=classification_report(Y_test,Y_pred)
print("Classfication rep by Extra Trees Classifier:")
print(class_r)
acc_s=accuracy_score(Y_test,Y_pred)
print("Accuracy score by  Extra Trees Classifier:",acc_s)

Confusion matrix by Extra Trees Classifier:
 [[ 79   3   3]
 [  3 134   0]
 [  0   1  18]]
Classfication rep by Extra Trees Classifier:
              precision    recall  f1-score   support

           0       0.96      0.93      0.95        85
           1       0.97      0.98      0.97       137
           2       0.86      0.95      0.90        19

    accuracy                           0.96       241
   macro avg       0.93      0.95      0.94       241
weighted avg       0.96      0.96      0.96       241

Accuracy score by  Extra Trees Classifier: 0.9585062240663901


In [47]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier
from sklearn.neighbors import KNeighborsClassifier
# create the sub models
estimators = []
model1 = LogisticRegression()
estimators.append(('log', model1))
model2 = DecisionTreeClassifier(criterion='gini',random_state=10)
estimators.append(('tree', model2))
model3 = SVC(kernel="rbf", C=90,gamma=0.1)
estimators.append(('svm', model3))
model4 = KNeighborsClassifier(n_neighbors=15, metric='euclidean')
estimators.append(('knn', model4))
print(estimators)
# create the ensemble model
ensemble = VotingClassifier(estimators)
ensemble.fit(X_train,Y_train)
Y_pred=ensemble.predict(X_test)
#print(Y_pred)

[('log', LogisticRegression()), ('tree', DecisionTreeClassifier(random_state=10)), ('svm', SVC(C=90, gamma=0.1)), ('knn', KNeighborsClassifier(metric='euclidean', n_neighbors=15))]


In [48]:
cm=confusion_matrix(Y_test,Y_pred)
print("Confusion matrix by Voting Classifier:\n",cm)
class_r=classification_report(Y_test,Y_pred)
print("Classfication rep by Voting Classifier:")
print(class_r)
acc_s=accuracy_score(Y_test,Y_pred)
print("Accuracy score by  Voting Classifier:",acc_s)

Confusion matrix by Voting Classifier:
 [[ 82   3   0]
 [ 10 127   0]
 [  2   4  13]]
Classfication rep by Voting Classifier:
              precision    recall  f1-score   support

           0       0.87      0.96      0.92        85
           1       0.95      0.93      0.94       137
           2       1.00      0.68      0.81        19

    accuracy                           0.92       241
   macro avg       0.94      0.86      0.89       241
weighted avg       0.93      0.92      0.92       241

Accuracy score by  Voting Classifier: 0.921161825726141


In [49]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import StackingClassifier
from sklearn.neighbors import KNeighborsClassifier
# create the sub models
level0 = []
model1 = LogisticRegression()
level0.append(('log', model1))
model2 = DecisionTreeClassifier(criterion='gini',random_state=10)
level0.append(('tree', model2))
model3 = SVC(kernel="rbf", C=90,gamma=0.1)
#level0.append(('svm', model3))
model4 = KNeighborsClassifier(n_neighbors=5, metric='euclidean')
level0.append(('knn', model4))
print(estimators)
level1=LogisticRegression()
# create the ensemble model
ensemble = StackingClassifier(estimators=level0, final_estimator=level1, cv=5,passthrough=False)
ensemble.fit(X_train,Y_train)
Y_pred=ensemble.predict(X_test)
#print(Y_pred)

[('log', LogisticRegression()), ('tree', DecisionTreeClassifier(random_state=10)), ('svm', SVC(C=90, gamma=0.1)), ('knn', KNeighborsClassifier(metric='euclidean', n_neighbors=15))]


In [50]:
cm=confusion_matrix(Y_test,Y_pred)
print("Confusion matrix by Stacking Classifier:\n",cm)
class_r=classification_report(Y_test,Y_pred)
print("Classfication rep by Stacking Classifier:")
print(class_r)
acc_s=accuracy_score(Y_test,Y_pred)
print("Accuracy score by  Stacking Classifier:",acc_s)

Confusion matrix by Stacking Classifier:
 [[ 79   3   3]
 [  2 135   0]
 [  0   2  17]]
Classfication rep by Stacking Classifier:
              precision    recall  f1-score   support

           0       0.98      0.93      0.95        85
           1       0.96      0.99      0.97       137
           2       0.85      0.89      0.87        19

    accuracy                           0.96       241
   macro avg       0.93      0.94      0.93       241
weighted avg       0.96      0.96      0.96       241

Accuracy score by  Stacking Classifier: 0.9585062240663901


In [51]:
from xgboost import XGBClassifier
Xg=XGBClassifier(random_state=10,max_depth=10,max_leaves=10)
Xg.fit(X_train,Y_train)
Y_pred=Xg.predict(X_test)

In [52]:
from sklearn.model_selection import GridSearchCV
parameter_space = {"n_estimators":[100,200,300,400],
                   "max_depth":[12,10,15],
                  "max_leaves":[5,10,15,20]}
    
    
clf = GridSearchCV(Xg,parameter_space,n_jobs=-1, cv=5)
clf.fit(X_train,Y_train)

GridSearchCV(cv=5,
             estimator=XGBClassifier(base_score=None, booster=None,
                                     callbacks=None, colsample_bylevel=None,
                                     colsample_bynode=None,
                                     colsample_bytree=None,
                                     early_stopping_rounds=None,
                                     enable_categorical=False, eval_metric=None,
                                     feature_types=None, gamma=None,
                                     gpu_id=None, grow_policy=None,
                                     importance_type=None,
                                     interaction_constraints=None,
                                     learning_rate=None,...
                                     max_cat_threshold=None,
                                     max_cat_to_onehot=None,
                                     max_delta_step=None, max_depth=10,
                                     max_leaves=10, m

In [53]:
clf.best_params_

{'max_depth': 12, 'max_leaves': 5, 'n_estimators': 100}

In [54]:
from xgboost import XGBClassifier
Xg=XGBClassifier(n_estimators=400,random_state=10,max_depth=10,max_leaves=5)
Xg.fit(X_train,Y_train)
Y_pred=Xg.predict(X_test)
cm=confusion_matrix(Y_test,Y_pred)
print("Confusion matrix by XGB Classifier:\n",cm)
class_r=classification_report(Y_test,Y_pred)
print("Classfication rep by XGB Classifier:")
print(class_r)
acc_s=accuracy_score(Y_test,Y_pred)
print("Accuracy score by  XGB Classifier:",acc_s)

Confusion matrix by XGB Classifier:
 [[ 79   3   3]
 [  2 135   0]
 [  0   1  18]]
Classfication rep by XGB Classifier:
              precision    recall  f1-score   support

           0       0.98      0.93      0.95        85
           1       0.97      0.99      0.98       137
           2       0.86      0.95      0.90        19

    accuracy                           0.96       241
   macro avg       0.93      0.95      0.94       241
weighted avg       0.96      0.96      0.96       241

Accuracy score by  XGB Classifier: 0.9626556016597511


In [55]:
sample.sort_values("Imp value",ascending=False)

Column  Imp value
10       Class Duration  22.138596
1                   Age  12.597797
0                Gender   9.111479
7   Financial Condition   7.732046
6         Load-shedding   7.451100
8         Internet Type   6.389937
9          Network Type   6.381141
11             Self Lms   5.656876
5              Location   5.649609
2       Education Level   5.109925
12               Device   4.260917
4            IT Student   4.145268
3      Institution Type   3.375307

In [56]:
from lazypredict.Supervised import LazyClassifier
clf=LazyClassifier(ignore_warnings=True,verbose=0,custom_metric=None)
models,predictions=clf.fit(X_train,X_test,Y_train,Y_test)

100%|██████████████████████████████████████████████████████████████████████████████████| 29/29 [00:01<00:00, 26.73it/s]


In [58]:
accuracy=pd.DataFrame(models)

In [59]:
accuracy

Accuracy  Balanced Accuracy ROC AUC  F1 Score  \
Model                                                                          
XGBClassifier                      0.96               0.95    None      0.96   
LabelPropagation                   0.96               0.95    None      0.96   
DecisionTreeClassifier             0.96               0.95    None      0.96   
LabelSpreading                     0.96               0.95    None      0.96   
ExtraTreesClassifier               0.96               0.95    None      0.96   
BaggingClassifier                  0.95               0.95    None      0.95   
RandomForestClassifier             0.95               0.93    None      0.95   
ExtraTreeClassifier                0.95               0.93    None      0.95   
LGBMClassifier                     0.93               0.93    None      0.93   
KNeighborsClassifier               0.85               0.78    None      0.85   
SVC                                0.81               0.76    None      0.81   
QuadraticDiscriminantAnalysis      0.76               0.75    None      0.76   
LinearDiscriminantAnalysis         0.71               0.69    None      0.71   
GaussianNB                         0.68               0.67    None      0.68   
LogisticRegression                 0.72               0.67    None      0.72   
NearestCentroid                    0.61               0.66    None      0.63   
BernoulliNB                        0.71               0.65    None      0.70   
AdaBoostClassifier                 0.68               0.63    None      0.68   
LinearSVC                          0.71               0.60    None      0.70   
CalibratedClassifierCV             0.71               0.58    None      0.70   
RidgeClassifier                    0.71               0.57    None      0.70   
RidgeClassifierCV                  0.71               0.57    None      0.70   
SGDClassifier                      0.66               0.57    None      0.64   
PassiveAggressiveClassifier        0.60               0.51    None      0.62   
Perceptron                         0.66               0.50    None      0.65   
DummyClassifier                    0.57               0.33    None      0.41   

                               Time Taken  
Model                                      
XGBClassifier                        0.08  
LabelPropagation                     0.04  
DecisionTreeClassifier               0.01  
LabelSpreading                       0.04  
ExtraTreesClassifier                 0.09  
BaggingClassifier                    0.02  
RandomForestClassifier               0.11  
ExtraTreeClassifier                  0.01  
LGBMClassifier                       0.10  
KNeighborsClassifier                 0.01  
SVC                                  0.03  
QuadraticDiscriminantAnalysis        0.00  
LinearDiscriminantAnalysis           0.01  
GaussianNB                           0.01  
LogisticRegression                   0.02  
NearestCentroid                      0.00  
BernoulliNB                          0.01  
AdaBoostClassifier                   0.06  
LinearSVC                            0.08  
CalibratedClassifierCV               0.28  
RidgeClassifier                      0.02  
RidgeClassifierCV                    0.01  
SGDClassifier                        0.01  
PassiveAggressiveClassifier          0.01  
Perceptron                           0.00  
DummyClassifier                      0.00

# APPLYING SMOTE

In [60]:
print("Before OverSampling, counts of label '1': ", (sum(Y_train == 1)))
print("Before OverSampling, counts of label '0': ", (sum(Y_train == 0)))
print("Before OverSampling, counts of label '2': ", (sum(Y_train == 2)))

# import SMOTE from imblearn library
from imblearn.over_sampling import SMOTE
sm = SMOTE(random_state = 10,k_neighbors=5)  #select any 5 observation and create synthetic data
X_train_res, Y_train_res = sm.fit_resample(X_train, Y_train)  #fit_resample will only work on training data
  
print('After OverSampling, the shape of train_X: ', (X_train_res.shape))
print('After OverSampling, the shape of train_y: ', (Y_train_res.shape))
  
print("After OverSampling, counts of label '1': ", (sum(Y_train_res == 1)))
print("After OverSampling, counts of label '0': ", (sum(Y_train_res == 0)))
print("After OverSampling, counts of label '2': ", (sum(Y_train_res == 2)))

Before OverSampling, counts of label '1':  488
Before OverSampling, counts of label '0':  395
Before OverSampling, counts of label '2':  81
After OverSampling, the shape of train_X:  (1464, 13)
After OverSampling, the shape of train_y:  (1464,)
After OverSampling, counts of label '1':  488
After OverSampling, counts of label '0':  488
After OverSampling, counts of label '2':  488


In [ ]:
from lazypredict.Supervised import LazyClassifier
clf=LazyClassifier(ignore_warnings=True,verbose=0,custom_metric=None)
models,predictions=clf.fit(X_train_res,X_test,Y_train_res,Y_test)

In [ ]:
accuracy=pd.DataFrame(models)

In [ ]:
accuracy

# USING XGB Classifier

In [ ]:
from xgboost import XGBClassifier
Xg=XGBClassifier(random_state=10,max_depth=10,max_leaves=10)
Xg.fit(X_train_res,Y_train_res)
Y_pred=Xg.predict(X_test)

In [ ]:
from sklearn.model_selection import GridSearchCV
parameter_space = {"n_estimators":[100,200,300,400],
                   "max_depth":[12,10,15],
                  "max_leaves":[5,10,15,20]}
    
    
clf = GridSearchCV(Xg,parameter_space,n_jobs=-1, cv=5)
clf.fit(X_train_res,Y_train_res)

In [ ]:
clf.best_params_

In [ ]:
from xgboost import XGBClassifier
Xg=XGBClassifier(n_estimators=100,random_state=10,max_depth=12,max_leaves=5)
Xg.fit(X_train_res,Y_train_res)
Y_pred=Xg.predict(X_test)
cm=confusion_matrix(Y_test,Y_pred)
print("Confusion matrix by XGB Classifier:\n",cm)
class_r=classification_report(Y_test,Y_pred)
print("Classfication rep by XGB Classifier:")
print(class_r)
acc_s=accuracy_score(Y_test,Y_pred)
print("Accuracy score by  XGB Classifier:",acc_s)

# USING Decision Tree

In [ ]:
Dt=DecisionTreeClassifier(criterion="gini",random_state=10,splitter="best")
# fit the model 
Dt.fit(X_train_res,Y_train_res)
Y_pred=Dt.predict(X_test)

In [ ]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
cm=confusion_matrix(Y_test,Y_pred)
print("Confusion matrix by Decision Tree :\n",cm)
class_r=classification_report(Y_test,Y_pred)
print("Classfication rep by Decision Tree :")
print(class_r)
acc_s=accuracy_score(Y_test,Y_pred)
print("Accuracy score by  Decision Tree :",acc_s)

# USING EXTRA TREE

In [ ]:
Et=ExtraTreesClassifier(n_estimators=100,random_state=10,bootstrap=True)
Et.fit(X_train_res,Y_train_res)
Y_pred=Et.predict(X_test)
cm=confusion_matrix(Y_test,Y_pred)
print("Confusion matrix by Extra Trees Classifier:\n",cm)
class_r=classification_report(Y_test,Y_pred)
print("Classfication rep by Extra Trees Classifier:")
print(class_r)
acc_s=accuracy_score(Y_test,Y_pred)
print("Accuracy score by  Extra Trees Classifier:",acc_s)